### ISSUE TITLE
Show Available Balance while Select Account

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/wormhole-ui#87]
### Importance

General

### Priority

Medium

### Description

<img width="759" alt="image" src="https://user-images.githubusercontent.com/16152305/133228488-07acdc7d-ce95-46a5-bdba-94617a14062c.png">

**Comment by sxlwar** [comment]
I don't think it's a good idea

There are several options for this idea:

1. wait for all queries to return results before displaying the list to the user; 
2. display only those accounts that have been queried, but of course, the query may or may not succeed.

The problem with the first option is that if a request fails, the list will not be displayed

The problem with the second option is that accounts that have not been queried will not appear in the list

The current implementation already shows the account balance to the user in placehold, but the problem is that no account changes are made without a re-query.
